// @generated by protoc-gen-es v1.10.0
// @generated from file ingestion/v1alpha/ingestion.proto (package ingestion.v1alpha, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Event } from "./event_pb.js";

/**
 * @generated from message ingestion.v1alpha.CollectEventsRequest
 */
export const CollectEventsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "ingestion.v1alpha.CollectEventsRequest",
  () => [
    { no: 1, name: "request_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "events", kind: "message", T: Event, repeated: true },
  ],
);

