// @generated by protoc-gen-connect-es v1.1.2 with parameter "target=ts"
// @generated from file ingestion/v1alpha/ingestion.proto (package ingestion.v1alpha, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CollectEventsRequest } from "./ingestion_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ingestion.v1alpha.IngestionService
 */
export const IngestionService = {
  typeName: "ingestion.v1alpha.IngestionService",
  methods: {
    /**
     * @generated from rpc ingestion.v1alpha.IngestionService.CollectEvents
     */
    collectEvents: {
      name: "CollectEvents",
      I: CollectEventsRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

